# Day 04 Group Worksheet
Sept 15, 2025

If you're working on CoCalc, it's good to rename your notebook with a fun group name and to include all group member names below so that you can easily find it later for reference.

* Group members:

## Task 1: Array warmups

**Task 1a)** Create the following 5x5 matrix where the border is filled with 1s and the inside is filled with 0s. 

I.e.,
```python
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```

In [ ]:
# Your code here


**Task 1b)** Create the following 8x8 checkerboard pattern matrix with alternating 0s and 1s.
```python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
# Your code here


**Task 1c)** Normalize the following array (make the values sum to 1)

In [ ]:
# Your code here

import numpy as np
arr = np.array([1, 2, 3, 4])



**Task 1d)** For the array `arr` below, find the mean of each row and each column. Your answers should be:
```python
Row means: [2. 5. 8.]
Column means: [4. 5. 6.]
```

In [ ]:
# Your code here

imprort numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


## Task 2: More Euler's method for motion
Today we are going to continue our work with Euler's method for motion by:
1. Introducing arrays as a way to store all of the motion data generated throughout a loop
1. Introducing collisions

### A collision and storing data in arrays
Below is a modified version of our Day 03 Euler's method code which introduces a collision, as well as storing our time, position and velocity data in arrays to be able to analyze after the main loop. After the code you will find your tasks related to this code.

In [ ]:
import numpy as np

# Constants and initial values
y0 = 0. # m
y_max = 100. # m

v0 = 15.3 # m/s

t0 = 0. # s
t_max = 50. # s
dt = 0.1 # s

# Our number of steps will also be our array size
n_steps = int((t_max - t0) / dt) + 1 # Total number of steps

# Arrays to store values throughout the simulation
y = np.zeros(n_steps)
v = np.zeros(n_steps)
t = np.zeros(n_steps)

# Store initial values in the array
y[0] = y0
v[0] = v0
t[0] = t0

# Main loop
for i in range(1, n_steps):
    
    y[i] = y[i-1] + v[i-1] * dt
    v[i] = v[i-1]
    t[i] = t[i-1] + dt
    
    if y[i] >= y_max:
        v[i] = -v[i]

        

**Task 2a)** Let's start by looking at the use of arrays in this version of the code. Add in any print or other diagnostic statements that you need to make sense of the code.

1. How are we storing the data generated throughout the loop? 
1. How is `[i-1]` being used in the loop? 
1. Why are we adding `1` to  `number_steps = int((t_max - t0) / dt)`?
1. Why are we using `range(1, n_steps)` instead of `range(n_steps)`? 

* Your notes here
* ..

**Task 2b)** How does the collision work? 

* Your notes here
* ..

**Task 2c)** From within the loop, use the variable `col_idx` to store the index associated with when the collision occured. Based on how the `t`, `y` and `v` arrays are built, we expect that this same index would apply to all three. Build a second loop after this main loop to print out the information from the five sequential steps consisting of the two steps immediately before the collision, the collision itself, and the two steps immediately after the collision. Below is an example of what this information could look like. 

```
t = 6.4 s,   y =  97.92 m,   v =  15.3 m/s
t = 6.5 s,   y =  99.45 m,   v =  15.3 m/s
t = 6.6 s,   y = 100.98 m,   v = -15.3 m/s
t = 6.7 s,   y =  99.45 m,   v = -15.3 m/s
t = 6.8 s,   y =  97.92 m,   v = -15.3 m/s
```

In [ ]:
# Your code here



## Multiple collisions

**Task 2d)** Introduce into your code a second collision barrier at `-100 m`, such that the object will be bouncing back and forth between the two barriers. Change `col_idx` to a list of the indices at which these collisions occur. And then, after the main loop, build a second loop that uses the indices stored in `col_idx` to output the times of each collision, in a format similar to what is shown below. In your output you are welcome to communicate the collision numbers with the first collision being numbered 0 or 1.
```
Collision number 1 occurred at  6.6 seconds
Collision number 2 occurred at 19.8 seconds
Collision number 3 occurred at 33.0 seconds
Collision number 4 occurred at 46.2 seconds
```

In [ ]:
# Your code here



## Group check-out for engagement points
Once you reach this point call one of the members of the teaching team over to ask you each a check-out question. 

Afterward (or while you are waiting), engage with the bonus tasks below.

## Bonus tasks if you have time. 

**Task 3:** Pick the tasks that are most interesting to you

1. For **Task 2c**, try to figure out how to use the function `enumerate()` in your `for` loop statement (e.g., `for .. in enumerate(col_idx):` as an alternate method of extracting the desired information out of `col_idx`.
1. In loops that take a long time to run, it can be helpful to provide progress feedback while the loop is running. Add code to one of your loops that prints some output every 100 iterations (e.g., `100 iterations complete`, `200 iterations complete`, etc,...).
1. For a trickier challenge than the above task, instead print output for every 10% complete (e.g., `10% complete`, `20% complete`, etc,...). Make sure that this is built in a responsive way so that if you update `t_max` or `dt`, it will still work correctly.

In [ ]:
# Your code here



In [ ]:
# Your code here



In [ ]:
# Your code here

